import './types/express-augmentation.js'

export { AuthManager, type GuardFactory, type UserProviderFactory } from './AuthManager.js'
export { AuthServiceProvider, type AuthProviderBindings } from './AuthServiceProvider.js'
export type { AuthConfig } from './config/AuthConfig.js'
export { defaultAuthConfig } from './config/defaultAuthConfig.js'
export type { Authenticatable } from './contracts/Authenticatable.js'
export type { Guard } from './contracts/Guard.js'
export type { StatefulGuard } from './contracts/StatefulGuard.js'
export type { UserProvider } from './contracts/UserProvider.js'
export type { SessionStore } from './contracts/SessionStore.js'
export type { CanResetPassword } from './contracts/CanResetPassword.js'
export type { MustVerifyEmail } from './contracts/MustVerifyEmail.js'
export type { SupportsBasicAuth } from './contracts/SupportsBasicAuth.js'
export { AuthorizationResponse } from './authorization/AuthorizationResponse.js'
export { attachAuthorizesRequests } from './authorization/AuthorizesRequests.js'
export {
  Gate,
  type AbilityCallback,
  type AfterCallback,
  type BeforeCallback,
  GateForUser,
} from './authorization/Gate.js'
export { Policy } from './authorization/Policy.js'
export { CallbackUserProvider } from './providers/CallbackUserProvider.js'
export { DatabaseUserProvider } from './providers/DatabaseUserProvider.js'
export { TokenGuard } from './guards/TokenGuard.js'
export { SessionGuard } from './guards/SessionGuard.js'
export { JwtProvider } from './jwt/JwtProvider.js'
export type { AtlexJwtPayload } from './jwt/JwtProvider.js'
export { JwtBlacklist } from './jwt/JwtBlacklist.js'
export type { BlacklistStore } from './jwt/BlacklistStore.js'
export { MemoryBlacklistStore } from './jwt/MemoryBlacklistStore.js'
export { RedisBlacklistStore } from './jwt/RedisBlacklistStore.js'
export { RefreshTokenRepository } from './jwt/RefreshTokenRepository.js'
export type { RefreshTokenRecord } from './jwt/RefreshTokenRecord.js'
export type { TokenPair } from './jwt/TokenPair.js'
export type { TokenAttemptResult } from './jwt/TokenAttemptResult.js'
export { parseDurationToSeconds } from './jwt/parseDuration.js'
export { Session } from './session/Session.js'
export { SessionManager } from './session/SessionManager.js'
export { SessionTableMigration } from './session/SessionTableMigration.js'
export { NullStore } from './session/stores/NullStore.js'
export { FileStore } from './session/stores/FileStore.js'
export { DatabaseStore } from './session/stores/DatabaseStore.js'
export { RedisStore } from './session/stores/RedisStore.js'
export { CookieStore } from './session/stores/CookieStore.js'
export { HashManager, type HashInfo } from './hashing/HashManager.js'
export type { Hasher } from './hashing/Hasher.js'
export { BcryptHasher } from './hashing/BcryptHasher.js'
export { Argon2Hasher } from './hashing/Argon2Hasher.js'
export { ScryptHasher } from './hashing/ScryptHasher.js'
export { PasswordBroker } from './passwords/PasswordBroker.js'
export { PasswordBrokerManager } from './passwords/PasswordBrokerManager.js'
export { DatabaseTokenRepository } from './passwords/DatabaseTokenRepository.js'
export {
  PasswordResetStatus,
  type PasswordResetStatus as PasswordResetStatusCode,
} from './passwords/PasswordResetStatus.js'
export { PasswordResetTableMigration } from './passwords/PasswordResetTableMigration.js'
export { EmailVerifier } from './verification/EmailVerifier.js'
export { StartSession } from './middleware/StartSession.js'
export { AuthMiddleware } from './middleware/AuthMiddleware.js'
export { AuthorizeMiddleware } from './middleware/AuthorizeMiddleware.js'
export { EnsureEmailIsVerified } from './middleware/EnsureEmailIsVerified.js'
export { ThrottleLogins } from './middleware/ThrottleLogins.js'
export { AuthenticationError } from './errors/AuthenticationError.js'
export { AuthorizationError } from './errors/AuthorizationError.js'
export { TokenExpiredError } from './errors/TokenExpiredError.js'
export { InvalidTokenError } from './errors/InvalidTokenError.js'
export { TokenBlacklistedError } from './errors/TokenBlacklistedError.js'
export { LockoutError } from './errors/LockoutError.js'
export type { AuthEventDispatcher } from './events/AuthEventDispatcher.js'
export { Attempting } from './events/Attempting.js'
export { Authenticated } from './events/Authenticated.js'
export { Login } from './events/Login.js'
export { Failed } from './events/Failed.js'
export { Logout } from './events/Logout.js'
export { Lockout } from './events/Lockout.js'
export { PasswordReset } from './events/PasswordReset.js'
export { PasswordResetLinkSent } from './events/PasswordResetLinkSent.js'
export { Verified } from './events/Verified.js'
export { Registered } from './events/Registered.js'
export { CurrentDeviceLogout } from './events/CurrentDeviceLogout.js'
export { OtherDeviceLogout } from './events/OtherDeviceLogout.js'
export { MemoryRateLimiter } from './support/MemoryRateLimiter.js'
export { parseCookies } from './support/parseCookies.js'
export { serializeCookie } from './support/serializeCookie.js'
export { secureCompare } from './support/secureCompare.js'
